# fly.toml app configuration file generated for letterunboxed on 2025-05-10T17:13:34+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'letterunboxed'
primary_region = 'sin'

[build]
  [build.args]
    GO_VERSION = '1.23.1'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
